# ArgoCD Installation
apiVersion: v1
kind: Namespace
metadata:
  name: argocd
---
apiVersion: v1
kind: Namespace
metadata:
  name: cms-app
---
# ArgoCD Server
apiVersion: apps/v1
kind: Deployment
metadata:
  name: argocd-server
  namespace: argocd
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: argocd-server
  template:
    metadata:
      labels:
        app.kubernetes.io/name: argocd-server
    spec:
      containers:
      - name: argocd-server
        image: quay.io/argoproj/argocd:v2.8.4
        ports:
        - containerPort: 8080
        - containerPort: 8083
        env:
        - name: ARGOCD_SERVER_INSECURE
          value: "true"
        - name: ARGOCD_SERVER_BASEHREF
          value: "/"
        command:
        - argocd-server
        - --insecure
        - --staticassets
        - /shared/app
        volumeMounts:
        - name: argocd-repo-server-tls
          mountPath: /app/config/tls
        - name: argocd-repo-server-tls
          mountPath: /app/config/ssh
        readinessProbe:
          httpGet:
            path: /healthz?full=true
            port: 8080
          initialDelaySeconds: 3
          periodSeconds: 30
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8080
          initialDelaySeconds: 3
          periodSeconds: 30
      volumes:
      - name: argocd-repo-server-tls
        emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: argocd-server
  namespace: argocd
spec:
  type: ClusterIP
  ports:
  - name: server
    port: 80
    targetPort: 8080
  - name: grpc
    port: 443
    targetPort: 8080
  selector:
    app.kubernetes.io/name: argocd-server
---
apiVersion: v1
kind: Service
metadata:
  name: argocd-server-metrics
  namespace: argocd
spec:
  type: ClusterIP
  ports:
  - name: metrics
    port: 8083
    targetPort: 8083
  selector:
    app.kubernetes.io/name: argocd-server
