name: Deploy to Kubernetes

on:
  push:
    branches: [ main ]
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to deploy to'
        required: true
        default: 'staging'
        type: choice
        options:
        - staging
        - production

env:
  KUBE_NAMESPACE: cms-app

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Helm
      uses: azure/setup-helm@v3
      with:
        version: 'latest'
        
    - name: Set up kubectl
      uses: azure/setup-kubectl@v3
      with:
        version: 'latest'
        
    - name: Configure kubectl
      run: |
        echo "${{ secrets.KUBE_CONFIG }}" | base64 -d > kubeconfig
        export KUBECONFIG=kubeconfig
        
    - name: Create namespace
      run: |
        kubectl create namespace ${{ env.KUBE_NAMESPACE }} --dry-run=client -o yaml | kubectl apply -f -
        
    - name: Deploy with Helm
      run: |
        helm upgrade --install cms-app ./helm/cms-app \
          --namespace ${{ env.KUBE_NAMESPACE }} \
          --set image.tag=${{ github.sha }} \
          --set image.repository=ghcr.io/quanmbl/project_cms_ci-cd_fpt_repoa \
          --wait --timeout=300s
          
    - name: Verify deployment
      run: |
        kubectl get pods -n ${{ env.KUBE_NAMESPACE }}
        kubectl get services -n ${{ env.KUBE_NAMESPACE }}
        kubectl get ingress -n ${{ env.KUBE_NAMESPACE }}
        
    - name: Run health check
      run: |
        kubectl wait --for=condition=ready pod -l app.kubernetes.io/name=cms-app -n ${{ env.KUBE_NAMESPACE }} --timeout=300s
        echo "Deployment successful!"
